name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 coverage bandit requests

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report

    - name: Lint code with flake8
      run: flake8 .

    - name: Security check with bandit
      run: bandit -r .

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Send notification to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        STATUS: ${{ job.status }}
      run: |
        if [ "$STATUS" == "success" ]; then
          MESSAGE="✅ CI/CD pipeline успешно выполнен."
        else
          MESSAGE="❌ CI/CD pipeline завершился с ошибками."
        fi
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d text="$MESSAGE"
